export const domRefs = {
	addProjectButton: document.querySelector('.add__btn-project'),
	projectContainer: document.querySelector('.projects'),
	formProject: document.querySelector('#form__project'),
	modalProject: document.querySelector('.modal-project'),
	modalCloseButton: document.querySelector('.modal__close'),
	inputProjectTitle: document.querySelector('#project_title'),
	todosContainer: document.querySelector('.todos'),
	workspaceTitleProject: document.querySelector(
		'.workspace__header-actions > h2',
	),
	buttonAddTask: document.querySelector('.workspace__header-actions > button'),
	sortTodo: document.querySelector('#sort_todo'),
	modalTodo: document.querySelector('.modal--todo'),
	buttonTodoClose: document.querySelector('.modal__close-todo'),
	formTodo: document.querySelector('#form__todo'),
	selectWrapper: document.querySelectorAll('.select-wrapper'),
	inputTodoTitle: document.querySelector('#todo_title'),
	inputTodoDescription: document.querySelector('#description'),
	inputTodoDueDate: document.querySelector('#due_date'),
	inputSelectPriority: document.querySelector('#select_priority'),
	inputTodoNote: document.querySelector('#notes'),
	emptyState: document.querySelector('.empty-state'),
	buttonChangeTodo: document.querySelector('.todos__edit'),
	selectTodo: document.querySelector('#sort_todo'),
};
